variables:
  - name: FORCE_COLOR
    value: 1
  - name: NodeVersion
    value: 14

resources:
  repositories:
    - repository: RushstackMainRepo
      type: github
      name: Microsoft/rushstack
      endpoint: 'GitHub (Rushbot)'
    - repository: 1esPipelines
      type: git
      name: 1ESPipelineTemplates/1ESPipelineTemplates
      ref: refs/tags/release

extends:
  template: v1/1ES.Official.PipelineTemplate.yml@1esPipelines
  parameters:
    pool:
      name: Azure-Pipelines-1ESPT-ExDShared
      os: windows
    stages:
      - stage:
        jobs:
          - job:
            templateContext:
              outputs:
                - output: pipelineArtifact
                  targetPath: $(Build.ArtifactStagingDirectory)/published-versions
                  artifactName: published-versions
            steps:
              - checkout: self
                persistCredentials: true
                path: rushstack-legacy
              - template: /common/config/azure-pipelines/templates/build.yaml@self
              - template: /common/config/azure-pipelines/templates/publish.yaml@self
                parameters:
                  VersionPolicyName: noRush
              - template: /common/config/azure-pipelines/templates/record-published-versions.yaml@self
