steps:
  - checkout: RushstackMainRepo
    path: rushstack
  - script: 'git config --local user.email rushbot@users.noreply.github.com'
    displayName: 'git config email'
    workingDirectory: '$(Agent.BuildDirectory)/rushstack'
  - script: 'git config --local user.name Rushbot'
    displayName: 'git config name'
    workingDirectory: '$(Agent.BuildDirectory)/rushstack'
  - script: 'node common/scripts/install-run-rush.js install --to repo-toolbox'
    displayName: 'Rush Install (rushstack)'
    workingDirectory: '$(Agent.BuildDirectory)/rushstack'
  - script: 'node common/scripts/install-run-rush.js build --verbose --production --to repo-toolbox'
    displayName: 'Rush Rebuild (rushstack)'
    workingDirectory: '$(Agent.BuildDirectory)/rushstack'
  - script: 'node $(Agent.BuildDirectory)/rushstack/repo-scripts/repo-toolbox/lib/start.js record-versions --out-file $(Build.ArtifactStagingDirectory)/published-versions/published-versions.json'
    displayName: 'Record Published Versions'
    workingDirectory: '$(Agent.BuildDirectory)/spfx-gulp-tools'
  # Published by the 1ES template
  # - publish: $(Build.ArtifactStagingDirectory)/published-versions
  #   artifact: published-versions
  #   displayName: 'Publish Artifact: published-versions'
